// Generated by C# from C:\Projects\GitHub\CSharpTest.Net.Tools\src\CmdToolExample\Example4.test-cs
// Example input/processing using inline C# program
// Xml Assembly: System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
